azure:
  activedirectory:
    tenant-id: acfc92c8-4e72-4af9-bff8-60d632079340
    client-id: 9d8a7ddf-05a6-495d-8e93-b781c2e4382f
    client-secret: ZJN.ev5.uGS15f3E5kCqg1P.__~~i8O7XR
    authorization-clients:
      web-api:
        scopes:
          - api://91c86feb-4df2-4106-8304-425b8ce058fa/.default
        authorization-grant-type: client-credentials